### ISSUE TITLE
etcd.conf not used

### ISSUE THREAD

**Issue by jtktam** [solarkennedy/etcd-packages#5]
I am running ubuntu trusty 

```
Linux beehive 3.16.0-33-generic #44~14.04.1-Ubuntu SMP Fri Mar 13 10:33:29 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

made the .deb package and installed it.  local testing works fine

```
⟫ etcdctl set /message "Bonjour monde"
Bonjour monde
⟫ etcdctl get /message "Bonjour monde"
Bonjour monde
⟫ curl -L -X PUT http://127.0.0.1:4001/v2/keys/message -d value="Hello World"
{"action":"set","node":{"key":"/message","value":"Hello World","modifiedIndex":23,"createdIndex":23},"prevNode":{"key":"/message","value":"Bonjour monde","modifiedIndex":22,"createdIndex":22}}
⟫ curl -L -X GET http://127.0.0.1:4001/v2/keys/message
{"action":"get","node":{"key":"/message","value":"Hello World","modifiedIndex":23,"createdIndex":23}}
```

I proceed to edit /etc/etcd.conf file, restart the service and it doesn't give error or use the values (I wanted to listen on the LAN, not 127.0.0.1)

**Comment by jtktam** [comment]
#
# etcd.conf
#
# This file will be sourced after the /etc/default/etcd system
# config file.  You can configure etcd via environment variables
# from this file.
#
# See the documentation in /usr/share/doc/etcd/ for details.

# sample etcd cluster config
export ETCD_INITIAL_CLUSTER_TOKEN="cluster1"

-----

sudo service etcd restart
 * Stopping etcd:
 * stopped
 * Starting etcd:
 * started

----

2015/04/02 09:37:01 no data-dir provided, using default data-dir ./default.etcd
2015/04/02 09:37:01 etcd: listening for peers on http://localhost:2380
2015/04/02 09:37:01 etcd: listening for peers on http://localhost:7001
2015/04/02 09:37:01 etcd: listening for client requests on http://localhost:2379
2015/04/02 09:37:01 etcd: listening for client requests on http://localhost:4001
2015/04/02 09:37:01 datadir is valid for the 2.0.1 format
2015/04/02 09:37:01 etcdserver: name = default
2015/04/02 09:37:01 etcdserver: data dir = default.etcd
2015/04/02 09:37:01 etcdserver: member dir = default.etcd/member
2015/04/02 09:37:01 etcdserver: heartbeat = 100ms
2015/04/02 09:37:01 etcdserver: election = 1000ms
2015/04/02 09:37:01 etcdserver: snapshot count = 10000
2015/04/02 09:37:01 etcdserver: advertise client URLs = http://localhost:2379,http://localhost:4001
2015/04/02 09:37:01 etcdserver: restart member ce2a822cea30bfca in cluster 7e27652122e8b2ae at commit index 8589
2015/04/02 09:37:01 raft: ce2a822cea30bfca became follower at term 16
2015/04/02 09:37:01 raft: newRaft ce2a822cea30bfca [peers: [], term: 16, commit: 8589, applied: 0, lastindex: 8589, lastterm: 16]
2015/04/02 09:37:01 etcdserver: added local member ce2a822cea30bfca [http://localhost:2380 http://localhost:7001] to cluster 7e2765$
2015/04/02 09:37:02 raft: ce2a822cea30bfca is starting a new election at term 16
2015/04/02 09:37:02 raft: ce2a822cea30bfca became candidate at term 17
2015/04/02 09:37:02 raft: ce2a822cea30bfca received vote from ce2a822cea30bfca at term 17
2015/04/02 09:37:02 raft: ce2a822cea30bfca became leader at term 17
2015/04/02 09:37:02 raft.node: ce2a822cea30bfca elected leader ce2a822cea30bfca at term 17
2015/04/02 09:37:02 etcdserver: published {Name:default ClientURLs:[http://localhost:2379 http://localhost:4001]} to cluster 7e2765$

**Comment by solarkennedy** [comment]
That is surprising. Can you dig a little deeper into why? Maybe a set -vx on the init script might reveal it?

**Comment by jtktam** [comment]
Tried a bunch of different settings in the conf file and finally got it working, maybe you can use this as a starting conf?

OLD (not working, the duplicate lines probably cause issues)

```
#
# etcd.conf
#
# This file will be sourced after the /etc/default/etcd system
# config file.  You can configure etcd via environment variables
# from this file.
#
# See the documentation in /usr/share/doc/etcd/ for details.

# sample etcd cluster config
#export ETCD_INITIAL_CLUSTER_TOKEN="cluster1"
#export ETCD_INITIAL_CLUSTER="infra1=http://10.1.1.1:2380,infra2=http://10.1.1.2:2380,infra3=http://10.1.1.3:2380"
#export ETCD_INITIAL_CLUSTER_TOKEN="cluster1"
#export ETCD_INITIAL_ADVERTISE_PEER_URLS="http://10.1.1.1:2380"
#export ETCD_LISTEN_PEER_URLS="http://10.1.1.1:2380"
```

NEW (working)

```
#
# etcd.conf
#
# This file will be sourced after the /etc/default/etcd system
# config file.  You can configure etcd via environment variables
# from this file.
#
# See the documentation in /usr/share/doc/etcd/ for details.

export ETCD_NAME="testlab"
export ETCD_LISTEN_PEER_URLS="http://10.0.0.1:7001"
export ETCD_LISTEN_CLIENT_URLS="http://10.0.0.1:4001"
export ETCD_INITIAL_ADVERTISE_PEER_URLS="http://10.0.0.1:7001"
export ETCD_INITIAL_CLUSTER="testlab=http://10.0.0.1:7001"
export ETCD_INITIAL_CLUSTER_STATE="new"
export ETCD_ADVERTISE_CLIENT_URLS="http://10.0.0.1:4001"
```

now listening on my eth0 :+1: 
```
2015/04/02 11:29:14 no data-dir provided, using default data-dir ./testlab.etcd
2015/04/02 11:29:14 etcd: listening for peers on http://10.0.0.1:7001
2015/04/02 11:29:14 etcd: listening for client requests on http://10.0.0.1:4001
2015/04/02 11:29:14 etcdserver: name = testlab
2015/04/02 11:29:14 etcdserver: data dir = testlab.etcd
2015/04/02 11:29:14 etcdserver: member dir = testlab.etcd/member
2015/04/02 11:29:14 etcdserver: heartbeat = 100ms
2015/04/02 11:29:14 etcdserver: election = 1000ms
2015/04/02 11:29:14 etcdserver: snapshot count = 10000
2015/04/02 11:29:14 etcdserver: advertise client URLs = http://10.0.0.1:4001
2015/04/02 11:29:14 etcdserver: initial advertise peer URLs = http://10.0.0.1:7001
2015/04/02 11:29:14 etcdserver: initial cluster = testlab=http://10.0.0.1:7001
2015/04/02 11:29:14 etcdserver: start member ceb5e9e76eb97be4 in cluster 65a9292a43de52c8
2015/04/02 11:29:14 raft: ceb5e9e76eb97be4 became follower at term 0
2015/04/02 11:29:14 raft: newRaft ceb5e9e76eb97be4 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2015/04/02 11:29:14 raft: ceb5e9e76eb97be4 became follower at term 1
2015/04/02 11:29:14 etcdserver: added local member ceb5e9e76eb97be4 [http://10.0.0.1:7001] to cluster 65a9292a43de52c8
2015/04/02 11:29:16 raft: ceb5e9e76eb97be4 is starting a new election at term 1
2015/04/02 11:29:16 raft: ceb5e9e76eb97be4 became candidate at term 2
2015/04/02 11:29:16 raft: ceb5e9e76eb97be4 received vote from ceb5e9e76eb97be4 at term 2
2015/04/02 11:29:16 raft: ceb5e9e76eb97be4 became leader at term 2
2015/04/02 11:29:16 raft.node: ceb5e9e76eb97be4 elected leader ceb5e9e76eb97be4 at term 2
2015/04/02 11:29:16 etcdserver: published {Name:testlab ClientURLs:[http://10.0.0.1:4001]} to cluster 65a9292a43de52c8
```

----

in the make file, I had problem with this line:

```
wget -nv --show-progress -c -O $(TARBALL) $(DOWNLOAD)
```

on trusty 14.04 (GNU Wget 1.15 built on linux-gnu)

wget: unrecognized option '--show-progress'

i changed it to 

```
wget -nv --progress=dot -c -O $(TARBALL) $(DOWNLOAD)
```

**Comment by jinnko** [comment]
@jtktam nice finds.

Ideally I didn't want to set any config that would cause a fresh install to deviate from the etcd defaults.  I'd prefer to leave it so.

Can you provide more info about how you were setting the config that wasn't getting picked up?  Did you find a bug in that part?

I have some other improvements to the init script that I'll push in the next couple of days, though none of that changes how the config is applied, so would be interested in more info from you.

**Comment by jtktam** [comment]
@jinnko please review my two suggestions above.  one of them is the makefile doesn't work on trusty wget install, the --show-progress is not supported

the other is the fact that the config file contains duplicate lines, i think that is the cause of why it didn't work out of the box

once i remove the duplicate lines and added the correct line, it works for me.  if you want to make a config file with the defaults, that would be ideal for a starting point as well.

**Comment by solarkennedy** [comment]
Please PR with any improvements to help other people who encounter the same things!

**Comment by jtktam** [comment]
I will do that. thanks.  working on it this weekend.

**Comment by jtktam** [comment]
PR sent, closing issue since it's running great for me now.
